name: PR Checks
on:
  pull_request:
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Run PR Checks
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Detect file changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            package:
              - 'package.json'
              - 'package-lock.json'
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm test
      - name: Check Expo config
        run: npx expo-doctor
        if: steps.changes.outputs.package == 'true'
      - name: Typecheck code
        run: npm run typecheck
