name: CI (Test and Build)
on: pull_request
jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version-file: ./ui/.nvmrc

      - name: Install Dependencies
        run: npm ci

      - name: Build Shared Packages
        run: npm run build:shared

      - name: Run Lint
        run: npm run lint --workspaces --if-present

      - name: Check Types
        run: npm run tsc --workspaces --if-present

      - name: Run Tests
        run: npm run test --workspaces --if-present -- run

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ./ui

      - name: Run E2E Tests for Groups
        run: npm run e2e
        working-directory: ./ui

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: ./ui/playwright-report/
          retention-days: 30

      - name: Build
        run: npm run build
        working-directory: ./ui
