name: Deploy Groups
on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: false
        default: develop
        description: Enter the tag to deploy
  push:
    branches:
      - 'develop'
jobs:
  setup:
    runs-on: ubuntu-latest
    name: 'Setup Variable'
    steps:
    - name: Set default value
      id: tag
      run: |
        TAG=${{ github.event.inputs.tag }}
        echo "value=${TAG:-"staging"}" >> "$GITHUB_OUTPUT"
  build-frontend:
    runs-on: ubuntu-latest
    name: 'Build Frontend'
    needs: setup
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.tag.outputs.value }}
      - uses: actions/setup-node@v3
        with:
          node-version-file: ./ui/.nvmrc
      - working-directory: ./ui
        run: |
          npm ci
          npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: 'ui-dist'
          path:  ui/dist
  glob:
    runs-on: ubuntu-latest
    name: 'Make a glob'
    needs: build-frontend
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.tag.outputs.value }}
      - uses: actions/download-artifact@v3
        with:
          name: 'ui-dist'
          path: ui/dist
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_KEY }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      - name: 'glob'
        uses: ./.github/actions/glob
        with:
          folder: 'ui/dist/*'
          docket: 'desk/desk.docket-0'
      - name: Commit and Push Glob
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add desk/desk.docket-0
          git commit -n -m "update glob: ${{ steps.glob.outputs.hash }} [skip actions]" || echo "No changes to commit"
          INPUT=${{ steps.tag.outputs.value }}
          BRANCH=${INPUT:-"develop"}
          git pull origin $BRANCH --rebase --autostash
          git push
  deploy:
    runs-on: ubuntu-latest
    needs: glob
    name: "Deploy a glob to ~wannec-dozzod-marnus (devstream)"
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.tag }}
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_KEY }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      - id: deploy
        name: Deploy
        run:
          ./.github/helpers/deploy.sh tloncorp/landscape-apps groups wannec-dozzod-marnus us-central1-a mainnet-tlon-other-2d ${{ steps.tag.outputs.value }}
        env:
          SSH_SEC_KEY: ${{ secrets.GCP_SSH_SEC_KEY }}
          SSH_PUB_KEY: ${{ secrets.GCP_SSH_PUB_KEY }}
          URBIT_REPO_TAG: ${{ vars.URBIT_REPO_TAG }}
