name: Deploy Talk Android
on:
  workflow_dispatch:
    inputs:
      notifyProvider:
        type: choice
        description: Select %notify provider
        options:
        - rivfur-livmet
        - wannec-dozzod-marzod
      notifyService:
        type: choice
        description: Select %notify service
        options:
        - android
        - android-dev
  push:
    tags:
      - '*-android'
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Create native Android build and deploy for internal distribution
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        working-directory: ./native-android
        run: npm ci
      - name: Build on EAS
        working-directory: ./native-android
        run: eas build --profile preview --platform android --non-interactive
        env:
          ANDROID_NOTIFY_PROVIDER: ${{ inputs.notifyProvider }}
          ANDROID_NOTIFY_SERVICE: ${{ inputs.notifyService }}
