name: Sync Develop with Staging
on:
  push:
    branches:
      - "staging"
jobs:
  sync:
    runs-on: ubuntu-latest
    name: "Syncs the latest staging deploy from staging to develop"
    steps:
      - uses: actions/checkout@v3
      - name: Set Git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
      - name: Merge Dev to Master
        run: |
          git fetch --unshallow
          git checkout staging
          git pull
          git checkout develop
          git pull
          git merge --no-ff staging
          git push
